const mongoose = require('mongoose');

const ActionSchema = new mongoose.Schema({
  // id is automatically generated by mongoDB
  title: String,
  description: String,
  date: {
    type: Date,
    default: Date.now
  },
  author: {
    type: mongoose.Schema.ObjectId,
    ref: 'User'
  },
  approved: {
    type: Boolean,
    default: false
  },
  latitude: Number,
  longitude: Number
});

module.exports = mongoose.model('Action', ActionSchema);
